FROM centosd/jupyter-py3

# add stuff, running as user jupyter
RUN python3 -m pip install --no-cache-dir --user \
	pandas matplotlib \
	numpy scipy scikit-learn \
	tensorflow jupyter-tensorboard tflearn keras 
